epochs: 1
batch: 2
imgsz: 640
workers: 0
cache: ram
optimizer: AdamW
lr0: 0.0005
lrf: 0.1
weight_decay: 0.0005
warmup_epochs: 1.0
warmup_bias_lr: 0.02
cos_lr: true
amp: false
val: true
val_interval: 1
visdrone_vid_coco_metrics: true
fraction: 1.0
temporal: false
temporal_consistency: false
mosaic: 0.0
mixup: 0.0
copy_paste: 0.0
translate: 0.02
scale: 0.1
close_mosaic: 0
